### ISSUE TITLE
Buffer space

### ISSUE THREAD

**Issue by WibblesDev** [royben/Resonance#50]
Trying to use the shared memory approach but I'm getting a buffer size issue. Is there a max size to the message?

Not enough space available in the buffer.
   at Resonance.ResonanceAdapter.Write(Byte[] data)
   at Resonance.ResonanceTransporter.OnEncodeAndWriteData(ResonanceEncodingInformation info)
   at Resonance.ResonanceTransporter.OnOutgoingMessage(ResonancePendingMessage pendingMessage)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Resonance.ResonanceTransporter.Send(Object message, ResonanceMessageConfig config)

**Comment by royben** [comment]
From what I can see there is no limit on the message size.
If you can send a sample project I will investigate.

**Comment by royben** [comment]
Fixed on `main`. The shared memory buffer was hardcoded to 1000 bytes, so anything
over ~996 bytes failed. It's now a constructor parameter defaulting to 1 MB:

    new SharedMemoryAdapter("MyAddress", 8 * 1024 * 1024)

Both sides must use the same size — the first to connect fixes the capacity.
